packages:
  - config/*
  - packages/*
  - packages/@core/*
  - packages/@core/ui-kit/*
  - packages/plugins/*
  - packages/common/*
  - apps/*

catalog:
  '@types/archiver': ^6.0.3
  '@types/html-minifier-terser': ^7.0.2
  '@types/node': ^22.10.2
  '@types/postcss-import': ^14.0.3
  '@types/nprogress': ^0.2.3
  '@types/sortablejs': ^1.15.8
  '@types/qrcode': ^1.5.5
  '@antfu/eslint-config': ^3.12.1
  '@manypkg/get-packages': ^2.2.2
  '@iconify/tailwind': ^1.2.0
  '@iconify/json': ^2.2.290
  '@iconify/vue': ^4.3.0
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.15
  '@intlify/core-base': ^10.0.5
  '@intlify/unplugin-vue-i18n': ^6.0.1
  '@jspm/generator': ^2.4.1
  '@changesets/git': ^3.0.2
  '@ctrl/tinycolor': ^4.1.0
  '@tanstack/vue-store': ^0.6.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@pnpm/workspace.read-manifest': ^1000.0.1
  '@vee-validate/zod': ^4.15.0
  '@vueuse/core': ^12.0.0
  '@vueuse/integrations': ^12.2.0
  autoprefixer: ^10.4.20
  archiver: ^7.0.1
  cheerio: 1.0.0
  chalk: ^5.4.0
  consola: ^3.3.0
  dotenv: ^16.4.7
  execa: ^9.5.2
  find-up: ^7.0.0
  ora: ^8.1.1
  pkg-types: ^1.2.1
  cssnano: ^7.0.6
  clsx: ^2.1.1
  defu: ^6.1.4
  postcss: ^8.4.49
  postcss-antd-fixes: ^0.2.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.2
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  tailwind-merge: ^2.6.0
  theme-colors: ^0.1.0
  class-variance-authority: ^0.7.1
  html-minifier-terser: ^7.2.0
  unbuild: ^3.0.1
  rollup: ^4.28.1
  rollup-plugin-visualizer: ^5.12.0
  vite: ^6.0.5
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: 4.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-pwa: ^0.21.1
  vite-plugin-vue-devtools: ^7.6.8
  axios: ^1.7.9
  dayjs: ^1.11.13
  nprogress: ^0.2.0
  sortablejs: ^1.15.6
  vee-validate: ^4.15.0
  zod: ^3.24.1
  zod-defaults: ^0.1.3
  watermark-js-plus: ^1.5.7
  lucide-vue-next: ^0.469.0
  echarts: ^5.6.0
  sass: ^1.83.1
  typescript: 5.6.3
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-i18n: ^10.0.5
  pinia: 2.2.2
  pinia-plugin-persistedstate: ^4.2.0
  ant-design-vue: ^4.2.6
  radix-vue: ^1.9.12
  qrcode: ^1.5.4
